#!/usr/bin/env bash
# This script loops "Best School" 10 times
var="Best School"
for var in "Best School"
do
    echo "$var"
    echo "$var"
    echo "$var"
    echo "$var"
    echo "$var"
    echo "$var"
    echo "$var"
    echo "$var"
    echo "$var"
    echo "$var"
done
