#!/usr/bin/env bash
# This script uses if elif and else statements in a while loop
i="0"
while [ $i -ge 10 ]
do
    echo "Best School"
    i=$(( i+1 ))
    if [ $i = 4 ]
    then
	echo "bad luck"
    elif [ $i = 8 ]
    then
	 echo "good luck"
    else
	echo "Best School"
	fi
done
