#!/usr/bin/env bash
# This script uses if elif and else statements in a while loop
i="0"
bad="bad luck"
good="good luck"
while [ $i -le 10 ]
do
    echo "Best School"
    i=$((i+1))
    if [ $i == 4 ]
    then
      echo "$bad"
    elif [ $i == 8 ]
    then
      echo "$good"
	fi
done
