#!/usr/bin/env bash
# This script uses if elif and else statements in a while loop
i="0"
bad="bad luck"
good="good luck"
while [ $i -le 10 ]
do
    i=$((i+1))
    if [ $i -eq 4 ]
    then
      echo "$bad"
    elif [ $i -eq 8 ]
    then
	echo "$good"
    else
	echo "Best School"
	fi
done
