#!/usr/bin/env bash
# This is a scrip that tells the time
hour="0"
while [ $hour -le 12 ]
do
    echo "Hour: $hour"
while [ $minute -le 59 ]
do
    echo "$minute"
    minute=$((minute+1))
done
hour=$((hour+1))
minute="1"
done
