#!/usr/bin/env bash
# This reads a file if it exits
file="school"
if [ ! -e $file ]
then
    echo "$file file does not exist"
else
    echo "$file file exists"
    if [ -s $file ]
    then
	echo "$file file is not empty"
	if [ -f $file ]
	then
	    echo "$file is a regular file"
	    fi
    else
	echo "$file file is empty"
	if [ -f $file ]
	then
	    echo "$file is a regular file"
	fi
    fi
fi
