#!/usr/bin/env bash
# This script creates a file which displays it's pid
echo ${PPID} > /var/run/myscript.pid

# Displays 'I hate the kill command', then deletes file and exits process when receiving a SIGTERM signal

trap "echo 'I hate the kill command'; rm /var/run/myscript.pid; exit" 15

# Displays 'Y U no love me?' when receiving a SIGINT signal

trap "echo Y U no love me?!" 2

# Displays 'To infinity and beyond' indefinitely

while true
do
    echo "To infinity and beyond"
    sleep 2
done

# Removes file and terminates itself when receiving SIGQUIT or SIGTERM signal

trap "rm /var/run/myscript.pid; exit" SIGQUIT
