#!/usr/bin/env bash
# This script manages the file 'manage_my_process'
# Starts file "manage_my_process" when "start" argument is passed.
firstarg="$1"
if [ "$firstarg" == "start" ]
then
    ./manage_my_process &
    echo ${PPID} >> /var/run/my_process.pid
    echo "manage_my_process started"
    # Stops file "manage_my_process" when "stop" argument is passed. 
    
elif [ "$firstarg" == "stop" ]
then
    pkill -f /var/run/my_process.pid
    rm -r /var/run/my_process.pid
    echo "manage_my_process stopped"
    # Restarts file "manage_my_process" when "restart" argument is passed.
    
elif [ "$firstarg" == "restart" ]
then
    pkill -f /var/run/my_process.pid
    rm /var/run/my_process.pid
    ./manage_my_process &
    echo ${PPID} >> /var/run/my_process.pid &
    echo "manage_my_process restarted"
    # Prints "Usage: manage_my_process {start|stop|restart}" if any other/no argument is passed
    
else
    echo "Usage: manage_my_process {start|stop|restart}"
fi
