#!/usr/bin/env bash
# This script manages the file 'manage_my_process'
s="$1"
# Starts file "manage_my_process" when "start" argument is passed.

if [ "$s" == "start" ]
then
    bash ./manage_my_process
    echo ${PPID} > /var/run/my_process.pid
    echo "manage_my_process started"
    # Stops file "manage_my_process" when "stop" argument is passed. 
    
elif [ "$s" == "stop" ]
then
    pkill -f manage_my_process
    rm /var/run/my_process.pid
    echo "manage_my_process stopped"
    # Restarts file "manage_my_process" when "restart" argument is passed.
    
elif [ "$s" == "restart" ]
then
    pkill -f manage_my_process
    rm /var/run/my_process.pid
    bash ./manage_my_process
    echo ${PPID} > /var/run/my_process.pid
    echo "manage_my_process restarted"
    # Prints "Usage: manage_my_process {start|stop|restart}" if any other/no argument is passed
    
else
    echo "Usage: manage_my_process {start|stop|restart}"
fi
