#!/usr/bin/env bash
# This script stops any script from running
pkill -f 4-to_infinity_and_beyond
status="$?"
if [ $status == 0 ]
then
    printf "0 One or more processes matched the criteria"
fi
if [ $status == 1 ]
then
    printf "1 No processes matched"
fi
