#!/usr/bin/env bash
# This script stops any script from running
status="$(echo $?)"
pkill -f 4-to_infinity_and_beyond
if [ "$status" == 0 ]
then
    echo "0 One or more processes matched the criteria"
    if [ "$status" == 1 ]
    then
    echo "1 No processes matched"
fi
fi
