#!/usr/bin/env bash
# This script stops any script from running
pkill -f 4-to_infinity_and_beyond
status="$?"
if [ $status == 0 ]
then
    echo "$status One or more processes matched the criteria"
fi
if [ $status == 1 ]
then
    printf "$status No processes matched\n" >&2
fi
