#!/usr/bin/env bash
# This script displays 'To infinity and beyond' indefinitely
# As well as adding in 'I am invincible' when receiving a SIGTERM
trap "echo I am invincible!!!" 15
while true
do
    echo "To infinity and beyond"
    sleep 2
done
